@carly_backend_HostAddress = http://localhost:5252

###
POST {{carly_backend_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "name": "Pawe³",
  "email": "pzalega@gmail.com",
  "password": "123456"
}

###
POST {{carly_backend_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "pzalega@gmail.com",
  "password": "123456"
}

###

GET {{carly_backend_HostAddress}}/vehicles
Accept: application/json

###
POST {{carly_backend_HostAddress}}/vehicles
Accept: application/json
Content-Type: application/json

{
  "name": ""
}

###
PATCH {{carly_backend_HostAddress}}/vehicles/3
Accept: application/json
Content-Type: application/json

{
  "name": "changedName"
}

###
DELETE {{carly_backend_HostAddress}}/vehicles/3
Accept: application/json

###
POST {{carly_backend_HostAddress}}/refuel
Content-Type: application/json
Accept: application/json

{
  "fillUpDate": "2024-12-23"
}

###
GET {{carly_backend_HostAddress}}/refuelings
Accept: application/json

###
GET {{carly_backend_HostAddress}}/fueltypes
